Update @ton/core, @ton/ton, and .spec.ts file
tact-lang/tact-template pull request #20
Opened 2024-05-05 08:17 UTC by howardpen9

https://github.com/tact-lang/tact-template/issues/19

2024-05-05 08:32 UTC, anton-trunov requested changes

2024-05-05 08:32 UTC, anton-trunov commented on package.json
> +    "@ton/core": "^0.56.3",
Let's remove this change. I added ~ on purpose here

2024-05-05 20:57 UTC, anton-trunov commented on yarn.lock
I think you need you update yarn.lock as well, after those changes in package.json

2024-05-10 02:58 UTC, howardpen9 commented
1

2024-05-13 09:28 UTC, howardpen9 commented
~~

2025-01-17 14:03 UTC, closed without merging