GitHub actions and Misti integration
tact-lang/tact-template pull request #34
Opened 2024-10-11 11:56 UTC by jubnzv

Closes #33

2024-10-11 13:18 UTC, jubnzv commented
For some reasons, the CI doesn't run for template repositories. I created a project using this template and will test CI there, right in the `main` branch: https://github.com/jubnzv/tact-template-ci-test.

2024-10-12 03:26 UTC, jubnzv commented
I have finished working on this. We still cannot run the CI in the template project, so here is an example of how the pipeline works:
- [Successful execution](https://github.com/jubnzv/tact-template-ci-test/actions/runs/11302301521/job/31437947499)
- [Warning generated](https://github.com/jubnzv/tact-template-ci-test/actions/runs/11301985992/job/31437164302#step:5:1)

2024-10-12 08:29 UTC, anton-trunov requested changes

2024-10-12 08:29 UTC, anton-trunov commented on .github/workflows/ci.yml
> +      - name: Run Misti
I'd move running Misti after the build. If the project does not build then it does not really make sense to run static analysis

2024-10-12 09:21 UTC, anton-trunov approved these changes

2024-10-12 09:21 UTC, merged